### Get all apartments
GET http://localhost:5555/api/apartments

### Get one apartment
GET http://localhost:5555/api/apartments/1

### Create apartment
POST http://localhost:5555/api/apartments
Content-Type: application/json

{
  "ownerid": 0,
  "address": "123 Main St",
  "monthlyrent": 800.00,
  "status": "AVAILABLE"
}

### Update apartment
PUT http://localhost:5555/api/apartments/1
Content-Type: application/json

{
  "ownerid": 0,
  "address": "456 Elm Street",
  "monthlyrent": 950.00,
  "status": "OCCUPIED"
}

### Delete apartment
DELETE http://localhost:5555/api/apartments/1

### Create owner
POST http://sistema-de-administraci-n-de-rentas-xyir-pekl0cpn5.vercel.app/api/owners
Content-Type: application/json

{
  "name": "Axel",
  "phone": "123456789",
  "email": "example@example",
  "governmentid": "INE",
  "password": "Evangelion"
}


### Login
POST https://sistema-de-administraci-n-de-rentas-xyir-pekl0cpn5.vercel.app/api/login
Content-Type: application/json

{
  "name": "Axel",
  "password": "12345678"
}

###
PUT http://localhost:3000/uploads/1696171523-contract.pdf
